//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eve_intel_map.IntelService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="ConnectionInfo", Namespace="http://schemas.datacontract.org/2004/07/eve_intel_server")]
    [System.SerializableAttribute()]
    public partial class ConnectionInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid ClientIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long OnlineClientsField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid ClientId {
            get {
                return this.ClientIdField;
            }
            set {
                if ((this.ClientIdField.Equals(value) != true)) {
                    this.ClientIdField = value;
                    this.RaisePropertyChanged("ClientId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long OnlineClients {
            get {
                return this.OnlineClientsField;
            }
            set {
                if ((this.OnlineClientsField.Equals(value) != true)) {
                    this.OnlineClientsField = value;
                    this.RaisePropertyChanged("OnlineClients");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="LocalKosInfo", Namespace="http://schemas.datacontract.org/2004/07/eve_intel_server")]
    [System.SerializableAttribute()]
    public partial class LocalKosInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string[] PilotNamesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SenderIdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long SystemIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string[] PilotNames {
            get {
                return this.PilotNamesField;
            }
            set {
                if ((object.ReferenceEquals(this.PilotNamesField, value) != true)) {
                    this.PilotNamesField = value;
                    this.RaisePropertyChanged("PilotNames");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((this.SenderIdField.Equals(value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long SystemId {
            get {
                return this.SystemIdField;
            }
            set {
                if ((this.SystemIdField.Equals(value) != true)) {
                    this.SystemIdField = value;
                    this.RaisePropertyChanged("SystemId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="KosPlayerInfo", Namespace="http://schemas.datacontract.org/2004/07/eve_intel_server")]
    [System.SerializableAttribute()]
    public partial class KosPlayerInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescriptionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private long LastKnownSystemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime LastKnownSystemTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PilotNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string PilotShipField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime PilotShipTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Guid SenderIdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Description {
            get {
                return this.DescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescriptionField, value) != true)) {
                    this.DescriptionField = value;
                    this.RaisePropertyChanged("Description");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public long LastKnownSystem {
            get {
                return this.LastKnownSystemField;
            }
            set {
                if ((this.LastKnownSystemField.Equals(value) != true)) {
                    this.LastKnownSystemField = value;
                    this.RaisePropertyChanged("LastKnownSystem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime LastKnownSystemTime {
            get {
                return this.LastKnownSystemTimeField;
            }
            set {
                if ((this.LastKnownSystemTimeField.Equals(value) != true)) {
                    this.LastKnownSystemTimeField = value;
                    this.RaisePropertyChanged("LastKnownSystemTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PilotName {
            get {
                return this.PilotNameField;
            }
            set {
                if ((object.ReferenceEquals(this.PilotNameField, value) != true)) {
                    this.PilotNameField = value;
                    this.RaisePropertyChanged("PilotName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string PilotShip {
            get {
                return this.PilotShipField;
            }
            set {
                if ((object.ReferenceEquals(this.PilotShipField, value) != true)) {
                    this.PilotShipField = value;
                    this.RaisePropertyChanged("PilotShip");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime PilotShipTime {
            get {
                return this.PilotShipTimeField;
            }
            set {
                if ((this.PilotShipTimeField.Equals(value) != true)) {
                    this.PilotShipTimeField = value;
                    this.RaisePropertyChanged("PilotShipTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid SenderId {
            get {
                return this.SenderIdField;
            }
            set {
                if ((this.SenderIdField.Equals(value) != true)) {
                    this.SenderIdField = value;
                    this.RaisePropertyChanged("SenderId");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="IntelService.IIntelService", CallbackContract=typeof(eve_intel_map.IntelService.IIntelServiceCallback))]
    public interface IIntelService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelService/Connect", ReplyAction="http://tempuri.org/IIntelService/ConnectResponse")]
        eve_intel_map.IntelService.ConnectionInfo Connect();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IIntelService/Connect", ReplyAction="http://tempuri.org/IIntelService/ConnectResponse")]
        System.Threading.Tasks.Task<eve_intel_map.IntelService.ConnectionInfo> ConnectAsync();
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IIntelService/BroadcastLocalKos")]
        void BroadcastLocalKos(eve_intel_map.IntelService.LocalKosInfo kosInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IIntelService/BroadcastLocalKos")]
        System.Threading.Tasks.Task BroadcastLocalKosAsync(eve_intel_map.IntelService.LocalKosInfo kosInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IIntelService/BroadcastKosPlayerInfo")]
        void BroadcastKosPlayerInfo(eve_intel_map.IntelService.KosPlayerInfo playerInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IIntelService/BroadcastKosPlayerInfo")]
        System.Threading.Tasks.Task BroadcastKosPlayerInfoAsync(eve_intel_map.IntelService.KosPlayerInfo playerInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntelServiceCallback {
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IIntelService/LocalKosInfo")]
        void LocalKosInfo(eve_intel_map.IntelService.LocalKosInfo kosInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IIntelService/KosPlayerInfo")]
        void KosPlayerInfo(eve_intel_map.IntelService.KosPlayerInfo playerInfo);
        
        [System.ServiceModel.OperationContractAttribute(IsOneWay=true, Action="http://tempuri.org/IIntelService/OnlineClientsUpdate")]
        void OnlineClientsUpdate(long onlineClients);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IIntelServiceChannel : eve_intel_map.IntelService.IIntelService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class IntelServiceClient : System.ServiceModel.DuplexClientBase<eve_intel_map.IntelService.IIntelService>, eve_intel_map.IntelService.IIntelService {
        
        public IntelServiceClient(System.ServiceModel.InstanceContext callbackInstance) : 
                base(callbackInstance) {
        }
        
        public IntelServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName) : 
                base(callbackInstance, endpointConfigurationName) {
        }
        
        public IntelServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, string remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public IntelServiceClient(System.ServiceModel.InstanceContext callbackInstance, string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, endpointConfigurationName, remoteAddress) {
        }
        
        public IntelServiceClient(System.ServiceModel.InstanceContext callbackInstance, System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(callbackInstance, binding, remoteAddress) {
        }
        
        public eve_intel_map.IntelService.ConnectionInfo Connect() {
            return base.Channel.Connect();
        }
        
        public System.Threading.Tasks.Task<eve_intel_map.IntelService.ConnectionInfo> ConnectAsync() {
            return base.Channel.ConnectAsync();
        }
        
        public void BroadcastLocalKos(eve_intel_map.IntelService.LocalKosInfo kosInfo) {
            base.Channel.BroadcastLocalKos(kosInfo);
        }
        
        public System.Threading.Tasks.Task BroadcastLocalKosAsync(eve_intel_map.IntelService.LocalKosInfo kosInfo) {
            return base.Channel.BroadcastLocalKosAsync(kosInfo);
        }
        
        public void BroadcastKosPlayerInfo(eve_intel_map.IntelService.KosPlayerInfo playerInfo) {
            base.Channel.BroadcastKosPlayerInfo(playerInfo);
        }
        
        public System.Threading.Tasks.Task BroadcastKosPlayerInfoAsync(eve_intel_map.IntelService.KosPlayerInfo playerInfo) {
            return base.Channel.BroadcastKosPlayerInfoAsync(playerInfo);
        }
    }
}
